name = 'columns'

[grid]
shape = [3, 3]
spacing = 1.0

[parameters]
erosion_coefficient = 4e-4
erosion_exponent = 1
ice_latent_heat = 3.34e5
ice_density = 917
gravity = 9.81
water_density = 1000
water_viscosity = 1.8e-3
friction_coefficient = 0.6
geothermal_heat_flux = 0.06
surface_energy = 3.4e-2
pore_throat_radius = 1e-6
melt_temperature = 273
sediment_thermal_conductivity = 6.27
ice_thermal_conductivity = 2
ice_clapeyron_slope = 7.2e-8 # units are K / Pa
frozen_fringe_porosity = 0.4
fringe_alpha = 3.1
fringe_beta = 1.3
permeability = 4.1e-17
film_thickness = 1e-8
till_grain_radius = 4e-5
particle_radius = 1e-6
critical_depth = 10
cluster_volume_fraction = 0.64

[solution_fields.soil__depth]
units = 'm'
initial = 0.0

[solution_fields.frozen_fringe__thickness]
units = 'm'
initial = 1e-3

[solution_fields.fringe__thermal_gradient]
units = 'K / m'
initial = 0.0

[solution_fields.transition_temperature]
units = 'K'
initial = 273.0

[solution_fields.fringe__saturation]
units = ''
initial = 1

[solution_fields.fringe__heave_rate]
units = 'm / s'
initial = 0.0

[solution_fields.fringe__growth_rate]
units = 'm / s'
initial = 0.0

[solution_fields.dispersed_layer__thickness]
units = 'm'
initial = 1e-3

[solution_fields.dispersed_layer__growth_rate]
units = 'm / s'
initial = 0.0

# For realistic use cases, these fields should be specified by input files,
# or added as fields to the grid manually during setup.
[static_inputs.glacier__thickness]
units = 'm'
value = 110

[static_inputs.glacier__effective_pressure]
units = 'Pa'
value = 100e3

[static_inputs.glacier__sliding_velocity_x]
units = 'm / s'
value = 1e-6

[static_inputs.glacier__sliding_velocity_y]
units = 'm / s'
value = 1e-6

[input_fields]
